apiVersion: apps/v1
kind: Deployment
metadata:
  name: apachemaven-rc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apachemaven
  template:
    metadata:
      name: apachemaven
      labels:
        app: apachemaven
    spec:
      containers:
      - name: apachemaven-pod
        image: allurimadhu1993/devops
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: apachemaven-rc
spec:
  type: NodePort
  selector:
    app: apachemaven
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 31257
